### ISSUE TITLE
Mod not working with Underground modpack

### ISSUE THREAD

**Issue by Av4lanche** [kagikn/GlowingPickupsSA#2]
Hi,

This mod does not work with the GTA: Underground mod.

Would it be possible to make this mod compatible with GTA: Underground? I'd like to feel the Vice City aesthetics within GTA: Underground

Thanks in advance!

**Comment by kagikn** [comment]
Yes, you're right. It doesn't work for me with the GTA: Underground mod, neither.

I guess it's because GTA: Underground increases the pickup limit with fastman92 limit adjuster.
I'll need to find how it increases the limit to make this mod compatible with compatible with GTA: Underground. I believe this wouldn't be too easy, though.

**Comment by Av4lanche** [comment]
If you could look into this, that would be awesome! Maybe I could also convince the creators to add it into the Underground mod pack, if they have your permission!

In my belief (and I think I can speak for others as well), it would bring a great aesthetic and good memories of Vice City.

**Comment by dkluin** [comment]
> I guess it's because GTA: Underground increases the pickup limit with fastman92 limit adjuster.
> I'll need to find how it increases the limit to make this mod compatible with compatible with GTA: Underground. I believe this wouldn't be too easy, though.

Hit me up on Discord (dkluin#3598) if you want help making your mod compatible :)

**Comment by kagikn** [comment]
Made this mod compatible with fastman92 limit adjuster ~~, but not compatible with GTA: Underground yet~~. (EDIT: I thought 7ae2719 doesn't make compatible with GTA: Underground, but actually does. Putting ASIs to the `scripts` folder doesn't work)
And thank you @dkluin, I Appreciate your info about how to `CPickup` pool address and the additional position member variables with FLA!

I forgot to make memory patterns for detecting if `Enable pickup limit patch` is enabled in `fastman92limitAdjuster_GTASA.ini`. I'll make ones when I can play the game (I won't be able to play games for a few days).

**Comment by Av4lanche** [comment]
Kagikn, perhaps you can send them over to me so I can test if it works properly, if that might be a good idea?

**Comment by kagikn** [comment]
Fixed in 7ae2719, c7d9abe and ebd3d72. Now closing.
